import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

public class Sort {
    public static List<String> defaults = new ArrayList<>();

    public static void setData() {
        defaults.add("Bootleg: Lậu");
        defaults.add("Cheat: gian lận");
        defaults.add("Copy-protection-technology: công nghệ chống sao chép");
        defaults.add("Copyright: bản quyền");
        defaults.add("Copyright ethics: tiêu chuẩn đạo đức");
        defaults.add("Creator: người sáng chế");
        defaults.add("Dishonest behavior: hành vi không trung thực");
        defaults.add("Duplicate: sao chép");
        defaults.add("Ethical standard: tiêu chuẩn đạo đức");
        defaults.add("Intellectural property: sở hữu trí tuệ");
        defaults.add("Integrity: liêm khiết chính trực");
        defaults.add("Ownership: quyền sở hữu");
        defaults.add("Plagiarism: đạo văn");
        defaults.add("Professional judgement: đánh giá chuyên môn");
        defaults.add("Public interest: lợi ích cộng đồng");
        defaults.add("Software copyright: bản quyền máy tính");
        defaults.add("Violate copyright law: luật vi phạm bản quyền");
        defaults.add("Welfare: phúc lợi");
        defaults.add("Apply for a patten: đăng ký bằng sáng chế");
        defaults.add("Be subject to disciplinary action: bị xử lý kỷ luật");
        defaults.add("Comply with: tuân theo");
        defaults.add("Be deceptive: dối trá");
        defaults.add("Defend the principle: bảo vệ nguyên tắc");
        defaults.add("Register a trademark: đăng ký thương hiệu bản quyền");
        defaults.add("Obey the law: tuân theo luật");
        defaults.add("Respect: tôn trọng");
        defaults.add("Take responsibility for: chịu trách nhiệm");
        defaults.add("To deal with problems: đối phó vấn đề");
        defaults.add("Unethical: vô đạo đức");
        defaults.add("Violate the public interest: vi phạm lợi ích cộng đồng");
        defaults.add("Withhold information: giữ kín thông tin");
        defaults.add("Alpha-testing: kiểm thử alpha");
        defaults.add("Aspect-oriented-programming: lập trình hướng đối tượng");
        defaults.add("Beta-testing: kiểm thử beta");
        defaults.add("Boot-loader: bộ tải khởi động");
        defaults.add("Cloud-computing: điện toán đám mây");
        defaults.add("Cloud-computing-infrastructure: cấu trúc điện toán đám mây");
        defaults.add("Control-structure: cấu trúc điều khiển");
        defaults.add("Documentation: tài liệu");
        defaults.add("Flow-chart: biểu đồ");
        defaults.add("Free-trial: thử nghiệm");
        defaults.add("Implementation: triển khai");
        defaults.add("In-app purcharse: tính năng mua");
        defaults.add("Instruction: câu lệnh");
        defaults.add("Language translator: trình biên dịch");
        defaults.add("Layout: giao diện");
        defaults.add("Maintenance: bảo trì");
        defaults.add("Object-oriented-programming: lập trình hướng đối tượng");
        defaults.add("Premium version: phiên bản cao cấp");
        defaults.add("Primitive data: dữ liệu nguyên thuỷ");
        defaults.add("Pseudocode: mã giả");
        defaults.add("Requirement analysis: phân tích nhu cầu");
        defaults.add("Sketch: phác thảo");
        defaults.add("Software development kit: bộ công cụ phát triển phần mềm");
        defaults.add("Template: mẫu");
        defaults.add("Virtual machine application: ứng dụng máy ảo");
        defaults.add("Visual diagram: biểu đồ mô hình");
        defaults.add("Analyze: phân tích");
        defaults.add("Code: mã");
        defaults.add("Define: xác định");
        defaults.add("Deploy: triển khai");
        defaults.add("Formalize: chính thức");
        defaults.add("Implement: thực thi");
        defaults.add("Maintain: bảo trì");
        defaults.add("Plan: kế hoạch");
        defaults.add("Prepare: chuẩn bị");
        defaults.add("Proofread: đọc và sửa bản in thử");
        defaults.add("Release: phát hành");
        defaults.add("Resize: điểu chỉnh kích cỡ");
        defaults.add("Test: kiểm tra");
        defaults.add("Tweak: điều chỉnh");
        defaults.add("Configuration: cấu hình");
        defaults.add("Installation: cài đặt");
        defaults.add("Maintenance: bảo trì");
        defaults.add("BIOS (basic input output system): hệ thống nhập xuất cơ bản");
        defaults.add("Device driver: thiết bị điều hành");
        defaults.add("Expansion card: thẻ mở rộng");
        defaults.add("Boot drive: ổ đĩa khởi động");
        defaults.add("Disk cleanup: làm sạch ổ đĩa");
        defaults.add("CMOS setup (complementery metal-oxide-semiconductor): thiết lập CMOS");
        defaults.add("Microsoft drive optimizer: tối ưu hoá ổ đĩa");
        defaults.add("Partision: phân vùng");
        defaults.add("Device manager: trình quản lý thiết bị");
        defaults.add("Video card: thẻ mạch video");
        defaults.add("Rescue disk: đĩa cứu hộ");
        defaults.add("Default: mặc định");
        defaults.add("Modem card: thẻ mạch modem");
        defaults.add("Maintain: bảo trì");
        defaults.add("Attach: đính kèm");
        defaults.add("Optimize: tối ưu");
        defaults.add("Reboot: khởi động lại");
        defaults.add("Defragment: tối ưu hoá ổ đĩa");
        defaults.add("Align: thẳng hàng");
        defaults.add("Insert: chèn");
        defaults.add("Backup: sao lưu");
        defaults.add("Process: xử lý");
        defaults.add("Secure: làm chặt");
        defaults.add("Boot: khởi động");
        defaults.add("Configue: cấu hình");
        defaults.add("Awkward: bất tiện");
        defaults.add("Constructive: tính xây dựng");
        defaults.add("Decent: tuyệt vời");
        defaults.add("Fragile: dễ vỡ");
        defaults.add("Gorgeous: lộng lẫy");
        defaults.add("Great: tuyệt");
        defaults.add("Impressive: ấn tượng");
        defaults.add("Outstanding: nổi bật");
        defaults.add("Powerful: sức mạnh lớn");
        defaults.add("Precise: chính xác");
        defaults.add("Premium: chất lượng cao");
        defaults.add("Responsive: nhạy");
        defaults.add("Satisfied: hài lòng");
        defaults.add("Sharp: sắc nét");
        defaults.add("Sleek: đẹp");
        defaults.add("Smooth: mượt");
        defaults.add("Snappy: sống động");
        defaults.add("Spacious: rộng rãi");
        defaults.add("Speedy: nhanh chóng");
        defaults.add("Unique: độc đáo");
        defaults.add("Vibrant: rực rỡ");
        defaults.add("Cons: nhược điểm");
        defaults.add("Feature: đặc điểm");
        defaults.add("Feedback: nhận xét");
        defaults.add("Good point: điểm tôt");
        defaults.add("Performance: hiệu suất");
        defaults.add("Pros: ưu điểm");
        defaults.add("Research: nghiên cứu");
        defaults.add("Submit: đưa ra để xem xét");
        defaults.add("Value: giá trị");
        defaults.add("Bad points: điểm xấu");
        defaults.add("Brightness: độ sáng");
        defaults.add("Durability: độ bền");
        defaults.add("Preview: xem trước");
        defaults.add("Rate: đánh giá");
    }

    public static void main(String[] args) {
        setData();
        Collections.sort(defaults);
        for (String str : defaults) {
            System.out.println(str);
        }
    }
}
